### ISSUE TITLE
Unsupported Operations since laravel 4.1.28

### ISSUE THREAD

**Issue by alwins0n** [franzliedke/auth-fluxbb#8]
after updating laravel framework to 4.1.28 the new UserProviderInterface obviously requires implementation of additional methods.

Error Message

Class FranzLiedke\AuthFluxBB\UserProvider contains 2 abstract methods and must therefore be declared abstract or implement the remaining methods (Illuminate\Auth\UserProviderInterface::retrieveByToken, Illuminate\Auth\UserProviderInterface::updateRememberToken)

**Comment by franzliedke** [comment]
Thanks for reporting! I should have noticed by myself when I heard about the BC break.

Well, this should now be fixed in [v1.0.3](https://github.com/franzliedke/auth-fluxbb/releases/tag/v1.0.3) - please update!

**Comment by alwins0n** [comment]
the problem persists:

Class FranzLiedke\AuthFluxBB\User contains 3 abstract methods and must therefore be declared abstract or implement the remaining methods (Illuminate\Auth\UserInterface::getRememberToken, Illuminate\Auth\UserInterface::setRememberToken, Illuminate\Auth\UserInterface::getRememberTokenName) 

FranzLiedke\AuthFluxBB\User still misses methods from Illuminate\Auth\UserInterface

**Comment by franzliedke** [comment]
Okay, this should be fixed in `@dev`. Apparently, two interfaces were changed.

I'll take a look at how these methods should be implemented tomorrow. For now they're just stubs.

**Comment by alwins0n** [comment]
hi franz,

will there be a 1.0.4 where the new functions are implemented? currently the package is not usable in a released version.

**Comment by franzliedke** [comment]
Thanks for the reminder - I tagged a release.
